[package]
name = "yaz0lib"
version = "0.1.2"
authors = ["Marime_Gui <lepro.guillaume@gmail.com>"]

[lib]
name = "yaz0lib"

[dependencies]
clap = "2.31.2"
ez_io = { git = "https://github.com/MarimeGui/ez_io" }
magic_number = { git = "https://github.com/MarimeGui/magic_number_rust.git" }